import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ChevronRight, ChevronLeft, X, Zap, Target, Users, LayoutDashboard, Database, Mic, Bot } from 'lucide-react';
import { cn } from '../lib/utils';
import { doc, getDoc, setDoc } from 'firebase/firestore';
import { db, auth } from '../lib/firebase';
import { handleFirestoreError, OperationType } from '../lib/utils';

interface TourStep {
  targetId: string;
  title: string;
  content: string;
  icon: React.ReactNode;
  position?: 'top' | 'bottom' | 'left' | 'right' | 'center';
}

const TOUR_STEPS: TourStep[] = [
  {
    targetId: 'tour-nav',
    title: 'Strategic Navigation',
    content: 'Switch between your Intelligence Dashboard, the Lead Vault, and your Strategic Diary here.',
    icon: <LayoutDashboard size={20} />,
    position: 'bottom'
  },
  {
    targetId: 'tour-magazine-switcher',
    title: 'Operational Focus',
    content: 'Filter your entire workspace by publication (Harvest SA, BBQ, or Leadership) to maintain deep contextual focus.',
    icon: <Zap size={20} />,
    position: 'bottom'
  },
  {
    targetId: 'tour-dashboard',
    title: 'Intelligence Feed',
    content: 'Your daily brief generated by AI. It analyzes market shifts and competitor poach signals for you.',
    icon: <Users size={20} />,
    position: 'top'
  },
  {
    targetId: 'tour-omni-bar',
    title: 'Stage 1: Listening',
    content: "Tap the mic in the Omni-Bar. Wendy’s orb turns from blue to active pink. She's transcribing your voice into text in real-time.",
    icon: <Mic size={20} />,
    position: 'top'
  },
  {
    targetId: 'tour-assistant',
    title: 'Stage 2: The Brain',
    content: "Wendy uses Gemini to parse your intent. She converts your words into structured actions like sourcing leads or drafting pitches.",
    icon: <Bot size={20} />,
    position: 'top'
  },
  {
    targetId: 'tour-assistant',
    title: 'Stage 3: Execution',
    content: "Wendy physically controls the screen. She'll navigate tabs, filter datasets, and trigger tools automatically based on your instructions.",
    icon: <LayoutDashboard size={20} />,
    position: 'top'
  },
  {
    targetId: 'tour-assistant',
    title: 'Stage 4: Voice Echo',
    content: "Wendy speaks back to you. She confirms completed tasks and briefs you on findings, allowing for a completely eyes-free experience.",
    icon: <Users size={20} />,
    position: 'top'
  }
];

export default function OnboardingTour() {
  const [currentStep, setCurrentStep] = useState(0);
  const [showTour, setShowTour] = useState(false);
  const [targetRect, setTargetRect] = useState<DOMRect | null>(null);

  useEffect(() => {
    const checkTourStatus = async () => {
      if (!auth.currentUser) return;
      
      const userId = auth.currentUser.uid;
      try {
        const userRef = doc(db, 'users', userId);
        const userSnap = await getDoc(userRef);
        
        // Always show tour for testing if it's not completed. 
        // In production, we'd ensure it only runs once per user.
        if (!userSnap.exists() || !userSnap.data()?.tourCompleted) {
          setShowTour(true);
        }
      } catch (error) {
        console.error('Error checking tour status:', error);
      }
    };
    checkTourStatus();
  }, []); // Run once on load

  useEffect(() => {
    if (showTour) {
      const step = TOUR_STEPS[currentStep];
      const element = document.getElementById(step.targetId);
      if (element) {
        element.scrollIntoView({ behavior: 'smooth', block: 'center' });
        setTimeout(() => {
          setTargetRect(element.getBoundingClientRect());
        }, 500); // Wait for scroll
      } else {
          setTargetRect(null);
      }
    }
  }, [showTour, currentStep]);

  const handleComplete = async () => {
    setShowTour(false);
    if (auth.currentUser) {
      const userId = auth.currentUser.uid;
      const path = `users/${userId}`;
      try {
        const userRef = doc(db, 'users', userId);
        await setDoc(userRef, { tourCompleted: true }, { merge: true });
      } catch (error) {
        handleFirestoreError(error, OperationType.WRITE, path);
      }
    }
  };

  if (!showTour) return null;

  const currentStepData = TOUR_STEPS[currentStep];

  return (
    <div className="fixed inset-0 z-[200] pointer-events-none">
      <AnimatePresence>
        {targetRect && (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="absolute inset-0 bg-black/60 pointer-events-auto"
            style={{
               clipPath: `polygon(
                 0% 0%, 100% 0%, 100% 100%, 0% 100%,
                 0% 100%,
                 ${targetRect.left - 8}px 100%,
                 ${targetRect.left - 8}px ${targetRect.top - 8}px,
                 ${targetRect.right + 8}px ${targetRect.top - 8}px,
                 ${targetRect.right + 8}px ${targetRect.bottom + 8}px,
                 ${targetRect.left - 8}px ${targetRect.bottom + 8}px,
                 ${targetRect.left - 8}px 100%,
                 0% 100%
               )`,
               fillRule: 'evenodd'
            }}
          />
        )}
      </AnimatePresence>

      <div className="absolute inset-0 flex items-center justify-center pointer-events-none p-4">
        <motion.div
          initial={{ opacity: 0, scale: 0.9, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          className="glass-panel w-full max-w-[360px] p-8 rounded-[2rem] border border-acc-gold/30 pointer-events-auto shadow-2xl relative bg-bg-deep/90 backdrop-blur-xl"
        >
          <button 
            onClick={() => setShowTour(false)}
            className="absolute top-6 right-6 text-text-tertiary hover:text-white transition-colors"
          >
            <X size={18} />
          </button>

          <div className="w-12 h-12 bg-acc-gold/10 rounded-2xl flex items-center justify-center mb-6 text-acc-gold border border-acc-gold/20 shadow-[0_0_20px_rgba(212,175,55,0.1)]">
            {currentStepData.icon}
          </div>

          <h4 className="text-[10px] font-black uppercase tracking-[0.3em] text-acc-gold mb-3">Step {currentStep + 1} of {TOUR_STEPS.length}</h4>
          <h3 className="text-xl font-bold text-text-primary mb-4 tracking-tight leading-tight">{currentStepData.title}</h3>
          <p className="text-sm text-text-secondary leading-relaxed mb-8 font-sans font-medium">
            {currentStepData.content}
          </p>

          <div className="flex items-center justify-between gap-4">
             <div className="flex gap-1.5">
                {TOUR_STEPS.map((_, i) => (
                   <motion.div 
                    key={i} 
                    animate={{ scale: i === currentStep ? 1.2 : 1, opacity: i === currentStep ? 1 : 0.3 }}
                    className={cn("w-1.5 h-1.5 rounded-full", i === currentStep ? "bg-acc-gold shadow-[0_0_10px_rgba(212,175,55,0.5)]" : "bg-white")} 
                   />
                ))}
             </div>
             
             <div className="flex gap-2">
                {currentStep > 0 && (
                   <button 
                    onClick={() => setCurrentStep(prev => prev - 1)}
                    className="p-3 bg-white/5 rounded-xl text-text-tertiary hover:bg-white/10 hover:text-white transition-all border border-white/10"
                   >
                      <ChevronLeft size={16} />
                   </button>
                )}
                {currentStep < TOUR_STEPS.length - 1 ? (
                   <button 
                    onClick={() => setCurrentStep(prev => prev + 1)}
                    className="flex items-center gap-2 px-6 py-3 bg-white text-black rounded-xl text-[10px] font-black uppercase tracking-widest hover:scale-105 transition-all active:scale-95"
                   >
                      <span>Next</span>
                      <ChevronRight size={14} />
                   </button>
                ) : (
                   <button 
                    onClick={handleComplete}
                    className="flex items-center gap-2 px-6 py-3 bg-acc-gold text-bg-deep rounded-xl text-[10px] font-black uppercase tracking-widest hover:scale-105 transition-all active:scale-95 shadow-[0_0_30px_rgba(212,175,55,0.4)]"
                   >
                      <span>Complete Setup</span>
                      <Zap size={14} />
                   </button>
                )}
             </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
